-- TEXIM ONE Supabase schema
-- Run this in Supabase SQL Editor after enabling automatic RLS.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  role text not null default 'member' check (role in ('member', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text not null default '',
  image_url text,
  author_id uuid references public.profiles(id) on delete set null,
  published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  event_date timestamptz not null,
  game text not null default 'Euro Truck Simulator 2',
  server text,
  route text,
  invite_link text,
  image_url text,
  organizer_id uuid references public.profiles(id) on delete set null,
  status text not null default 'upcoming' check (status in ('upcoming', 'live', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  truckersmp_username text not null,
  discord_username text not null,
  age integer check (age >= 13 and age <= 100),
  experience text,
  reason text,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.event_participants (
  event_id bigint not null references public.events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

-- Helper used by RLS policies. SECURITY DEFINER avoids recursive profile policies.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- Automatically create a profile whenever a user registers.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    nullif(new.raw_user_meta_data ->> 'username', ''),
    coalesce(
      nullif(new.raw_user_meta_data ->> 'display_name', ''),
      nullif(new.raw_user_meta_data ->> 'username', '')
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Keep updated_at current.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists news_set_updated_at on public.news;
create trigger news_set_updated_at before update on public.news
for each row execute procedure public.set_updated_at();

drop trigger if exists events_set_updated_at on public.events;
create trigger events_set_updated_at before update on public.events
for each row execute procedure public.set_updated_at();

drop trigger if exists applications_set_updated_at on public.applications;
create trigger applications_set_updated_at before update on public.applications
for each row execute procedure public.set_updated_at();

-- RLS: explicit policies keep the public site readable while protecting writes.
alter table public.profiles enable row level security;
alter table public.news enable row level security;
alter table public.events enable row level security;
alter table public.applications enable row level security;
alter table public.event_participants enable row level security;

-- Profiles
drop policy if exists "profiles are publicly readable" on public.profiles;
create policy "profiles are publicly readable"
on public.profiles for select
using (true);

drop policy if exists "users can update their profile" on public.profiles;
create policy "users can update their profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "admins can manage profiles" on public.profiles;
create policy "admins can manage profiles"
on public.profiles for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- News
drop policy if exists "published news is public" on public.news;
create policy "published news is public"
on public.news for select
using (published = true or public.is_admin());

drop policy if exists "admins can manage news" on public.news;
create policy "admins can manage news"
on public.news for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Events
drop policy if exists "events are public" on public.events;
create policy "events are public"
on public.events for select
using (true);

drop policy if exists "admins can manage events" on public.events;
create policy "admins can manage events"
on public.events for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Applications
drop policy if exists "users can create their own application" on public.applications;
create policy "users can create their own application"
on public.applications for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can view their own applications" on public.applications;
create policy "users can view their own applications"
on public.applications for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "users can update their own pending application" on public.applications;
create policy "users can update their own pending application"
on public.applications for update
to authenticated
using (auth.uid() = user_id and status = 'pending')
with check (auth.uid() = user_id and status = 'pending');

drop policy if exists "admins can manage applications" on public.applications;
create policy "admins can manage applications"
on public.applications for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Event participants
drop policy if exists "participants are public" on public.event_participants;
create policy "participants are public"
on public.event_participants for select
using (true);

drop policy if exists "users can join events" on public.event_participants;
create policy "users can join events"
on public.event_participants for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can leave events" on public.event_participants;
create policy "users can leave events"
on public.event_participants for delete
to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "admins can manage participants" on public.event_participants;
create policy "admins can manage participants"
on public.event_participants for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Storage: the avatars bucket is public for reading. Authenticated users may only
-- create, replace, and delete files inside their own <user-id>/ folder.
drop policy if exists "Public can view avatars" on storage.objects;
create policy "Public can view avatars"
on storage.objects for select
to public
using (bucket_id = 'avatars');

drop policy if exists "Users select own avatar" on storage.objects;
create policy "Users select own avatar"
on storage.objects for select
to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "Users upload own avatar" on storage.objects;
create policy "Users upload own avatar"
on storage.objects for insert
to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "Users update own avatar" on storage.objects;
create policy "Users update own avatar"
on storage.objects for update
to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "Users delete own avatar" on storage.objects;
create policy "Users delete own avatar"
on storage.objects for delete
to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

-- Useful indexes
create index if not exists news_published_idx on public.news (published, published_at desc);
create index if not exists events_date_idx on public.events (event_date);
create index if not exists events_status_idx on public.events (status);
create index if not exists applications_user_idx on public.applications (user_id);
create index if not exists applications_status_idx on public.applications (status);
create index if not exists participants_user_idx on public.event_participants (user_id);
